language: general

services:
  - docker

branches:
  only:
    - master

before_script:
  - chmod +x *.sh

jobs:
  include:
    - stage: test
      name: "Docker: Bioconductor 3.9"
      script: tag="bioc-3.9" ./docker.sh
    - stage: test
      name: "Docker: Bioconductor 3.8"
      script: tag="bioc-3.8" ./docker.sh
    - stage: test
      name: "Docker: Bioconductor 3.7"
      script: tag="bioc-3.7" ./docker.sh

matrix:
  fast_finish: true

after_failure:
  - ./docker-failure.sh

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
