language: general

services:
  - docker

before_install:
  - docker pull acidgenomics/basejump
  - docker images

script:
  - docker run -ti --user="bioc" --volume="${PWD}:/basejump" --workdir="/basejump" acidgenomics/basejump Rscript -e 'source("travis-docker.R")'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
